#pragma once

#include <chowdsp_dsp_utils/Resampling/chowdsp_BaseResampler.h>
#include <CDSPResampler.h>
#include <vector>
#include <memory>
#include <cmath>

#if defined (__APPLE__)
 #include <Accelerate/Accelerate.h>
#endif

/**
 * A custom resampler class wrapping r8brain-free-src (Voxengo)
 * that implements the chowdsp::ResamplingTypes::BaseResampler interface.
 */
class R8BrainResampler : public chowdsp::ResamplingTypes::BaseResampler
{
public:
    R8BrainResampler() = default;
    ~R8BrainResampler() override = default;

    /** Prepares the resampler for a given input sample rate */
    void prepare (double sampleRate, double startRatio = 1.0) override
    {
        fs = sampleRate;
        ratio = startRatio;

        // Pre-allocate a generous double buffer (16384 elements) to prevent dynamic resizing in the audio thread
        inputDouble.resize (16384, 0.0);

        recreateResampler();
    }

    /** Returns the latency of the resampler in samples at the input rate */
    [[nodiscard]] int getLatencySamples() const noexcept override
    {
        return resampler != nullptr ? resampler->getInLenBeforeOutPos (0) : 0;
    }

    /** Resets the state of the resampler */
    void reset() override
    {
        if (resampler != nullptr)
            resampler->clear();
    }

    /** Sets the ratio of the output sample rate over input sample rate */
    void setResampleRatio (float newRatio) override
    {
        double targetRatio = (double) newRatio;
        if (std::abs (ratio - targetRatio) > 1e-5)
        {
            ratio = targetRatio;
            recreateResampler();
        }
    }

    /** Returns the ratio of the output sample rate over input sample rate */
    [[nodiscard]] float getResampleRatio() const noexcept override
    {
        return (float) ratio;
    }

    /** Processes a buffer of samples.
     *  Converts input float samples to double, runs the r8brain resampler,
     *  and converts the generated double samples back to float.
     *
     *  @return the number of output samples generated by the resampler.
     */
    size_t process (const float* input, float* output, size_t numSamples) noexcept override
    {
        if (resampler == nullptr)
            return 0;

        // Ensure we do not exceed the pre-allocated buffer size to prevent dynamic allocations
        size_t samplesToProcess = std::min (numSamples, inputDouble.size());
        jassert (numSamples <= inputDouble.size());

        // Copy float input to double input using hardware-accelerated vDSP on Apple devices
#if defined (__APPLE__)
        vDSP_vspdp (input, 1, inputDouble.data(), 1, (vDSP_Length) samplesToProcess);
#else
        for (size_t i = 0; i < samplesToProcess; ++i)
            inputDouble[i] = (double) input[i];
#endif

        double* outputDoublePtr = nullptr;
        int outSamples = resampler->process (inputDouble.data(), (int) samplesToProcess, outputDoublePtr);

        // Copy double output to float output
        if (outputDoublePtr != nullptr && outSamples > 0)
        {
#if defined (__APPLE__)
            vDSP_vdpsp (outputDoublePtr, 1, output, 1, (vDSP_Length) outSamples);
#else
            for (int i = 0; i < outSamples; ++i)
                output[i] = (float) outputDoublePtr[i];
#endif
        }

        return (size_t) outSamples;
    }

private:
    void recreateResampler()
    {
        double srcRate = fs;
        double dstRate = fs * ratio;

        // Minimum block size of 4096 is enforced in PluginProcessor.cpp.
        // We set maxInLen to 8192 to safely handle block sizes and resampling ratio variations.
        int maxInLen = 8192;

        // Use r8b::CDSPResampler directly with optimized low-latency settings.
        // - ReqTransBand = 12.0% (flat response up to 21.12 kHz at 48kHz target rate)
        // - ReqAtten = 100 dB (extremely clean stop-band attenuation)
        // - ReqPhase = r8b::fprLinearPhase (linear-phase for perfect phase response)
        resampler = std::make_unique<r8b::CDSPResampler> (srcRate, dstRate, maxInLen, 12.0, 100.0, r8b::fprLinearPhase);
    }

    double fs = 48000.0;
    double ratio = 1.0;
    std::unique_ptr<r8b::CDSPResampler> resampler;
    std::vector<double> inputDouble;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (R8BrainResampler)
};
